name = "generador-lettering"
type = "webpack"
account_id = "your-account-id"
workers_dev = true
route = "generador-lettering.pages.dev/*"
zone_id = "your-zone-id"

[site]
bucket = ".next/static"
entry-point = "."

[build]
command = "npm run build"
upload.format = "service-worker"

[env.production]
workers_dev = false
route = "generador-lettering.pages.dev/*"
